export default function Help() {
    return (
        <>
            <h2>Help</h2>
            <h3>How to play</h3>
            <p>Sorry I am very Lazy to explain how to play this game. But you can fidget around the page to figure it out.</p>
            <p>Here is text generated by ChatGPT that explains what is "Cryptogram"</p>

            <h3>What is Cryptogram (according to ChatGPT)</h3>
            <p>A cryptogram is a type of puzzle that involves encoding or encrypting a message in such a way that it becomes difficult to read without the proper key or decryption method. The term "cryptogram" is often used interchangeably with "cipher" or "code."</p>
            <p>Cryptograms can take various forms and use different techniques for encryption. Some common types include:</p>
            <p><b>1.Substitution Cipher:</b> In a substitution cipher, each letter in the plaintext (the original message) is replaced with another letter according to a predetermined key or rule. For example, in a Caesar cipher, each letter is shifted a certain number of positions down or up the alphabet.</p>
            <p><b>2.Transposition Cipher:</b> In a transposition cipher, the letters of the plaintext are rearranged according to a specific system. For example, letters might be written in a grid and then read out in a different order.</p>
            <p><b>3.Polyalphabetic Cipher:</b> A polyalphabetic cipher uses multiple alphabets to encode the message. Each letter may be encrypted differently depending on its position in the plaintext and the key used.</p>
            <p><b>4.Modern Cryptography:</b> Modern cryptographic techniques often involve complex algorithms and mathematical principles to secure data. These methods go beyond simple substitution and transposition, utilizing techniques such as public-key cryptography, hashing, and digital signatures.</p>
            <p>Cryptograms are often used as puzzles or brain teasers, where the goal is to decrypt the message and reveal the original text. They can be found in puzzle books, newspapers, and online puzzle websites. Additionally, cryptograms have historical significance and have been used throughout history to protect sensitive information and communicate secretly.</p>
        </>
    )
}